name: Deploy Release

# The job builds the mat-addons, publishes in on npmjs and deploys a new demo on ghpages

on:
  push:
    tags: ["v.*"]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# todo the version does not yet increase in package.json
