name: Deploy Release

# The job builds the mat-addons, publishes in on npmjs and deploys a new demo on ghpages

on:
  push:
    tags: ["v.*"]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build:mat-add
      - run: npm install --no-optional
      - run: npm run build:demo
      - run: echo 'Publishing Tag ${GITHUB_REF:12} to NPM Public'
      - run: npm publish ./dist/material-addons --access public --tag ${GITHUB_REF:12}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run publish:demo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
